### ISSUE TITLE
How to use -planPath via GitHub actions

### ISSUE THREAD

**Issue by JinoArch** [Official-James/rover-terraform-action#1]
Hi 

I wonder how can we provide planPath via GitHub actions. Any specific env variables?
Like the one used below:

`$ docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath mytfplan`

**Comment by Official-James** [comment]
@JinoArch seems possible. We would have to create a separate shell script and add an if statement to the dockerfile to execute if env variable is not null.

**Comment by sunnyoswalcro** [comment]
@JinoArch were you able to get it working ?

**Comment by sunnyoswalcro** [comment]
https://github.com/im2nguyen/rover/issues/115#issuecomment-1218169994 works.

**Comment by JinoArch** [comment]
Works. Please close this thanks.
